baseURL = 'https://kyberwerk.net/'
languageCode = 'en-us'
title = 'KYBERWERK'
theme = 'kyber'

[params]
tagline = "Build cool shit. Put it on the net."
phonetic = "(kai-ba-work)"
youtube = "https://www.youtube.com/channel/UCtDCHoi4QGNj2gG4obC8fVg"
mail = "info@telekom.de"
