baseURL = 'https://servopunk.net/'
languageCode = 'en-us'
title = 'SERVOPUNK'
theme = 'kyber'

[params]
tagline = "Build cool shit. Put it on the net."
youtube = "https://www.youtube.com/@SERVOPUNK"
mail = "info@servopunk.net"

